
import java.awt.Component;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.util.Date;
import java.util.UUID;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mukkun
 */
public class VenuePopup extends javax.swing.JFrame {

    /**
     * Creates new form addVenuePopup
     */
    Dashboard parent;
    File image = null;
    String action = "";
    Venue v;

    public VenuePopup(Dashboard p) {
        parent = p;
        parent.setEnabled(false);
        initComponents();
        action = "ADD";
    }

    public VenuePopup(Dashboard p, String uuid) {
        parent = p;
        parent.setEnabled(false);
        initComponents();
        title.setText("Edit Event Venue");
        btn.setText("Update Venue");
        action = "EDIT";
        v = Dashboard.Venues.get(uuid);
        siteName.setText(v.getSiteName());
        city.setText(v.getCity());
        address.setText(v.getAddress());
        capacity.setText(String.valueOf(v.getCapacity()));
        int i = 0;
        while (type.getItemAt(i) != null) {
            if (type.getItemAt(i).equals(v.getType())) {
                type.setSelectedIndex(i);
                break;
            }
            i++;
        }
        image = new File(v.getImgPath());
        imgPath.setText(v.getImgPath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        btn = new javax.swing.JButton();
        siteName = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        errMsg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        imgPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        title.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Add Event Venue");
        title.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Site Name");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("City");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Address");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Capacity");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Type");

        type.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hall", "Ballroom", "Bar/Club", "Hotel", "Conference centre", "Stadium/Arena", "Park/Field" }));

        btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn.setText("Add Venue");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        errMsg.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        errMsg.setForeground(new java.awt.Color(255, 51, 51));
        errMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Site Image");

        jButton2.setText("Browse Images");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        imgPath.setForeground(new java.awt.Color(0, 153, 102));
        imgPath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(siteName)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(siteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgPath, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        if (siteName.getText().trim().length() == 0) {
            errMsg.setText("Enter Site Name");
        } else if (city.getText().trim().length() == 0) {
            errMsg.setText("Enter City");
        } else if (address.getText().trim().length() == 0) {
            errMsg.setText("Enter Address");
        } else if (capacity.getText().trim().length() == 0) {
            errMsg.setText("Enter Capacity");
        } else if (!Utils.isStringInt(capacity.getText().trim())) {
            errMsg.setText("Capacity must be a number");
        } else if (image == null) {
            errMsg.setText("Upload site picture");
        } else {
            if (action.equals("ADD")) {
                add();
            } else if (action.equals("EDIT")) {
                edit();
            }
        }
    }//GEN-LAST:event_btnActionPerformed

    private void add() {
        try {
            String uuid = UUID.randomUUID().toString();
            String imgPath = "images/venues/" + uuid + image.getName().substring(image.getName().lastIndexOf("."), image.getName().length());
            File source = new File(image.getPath());
            File dest = new File(imgPath);
            Utils.copyFile(source, dest);

            PreparedStatement stmt = Dashboard.conn.prepareStatement("INSERT INTO venues VALUES (?,?,?,?,?,?,?,?)");
            stmt.setString(1, uuid);
            stmt.setString(2, siteName.getText());
            stmt.setString(3, city.getText());
            stmt.setString(4, address.getText());
            stmt.setString(5, (String) type.getSelectedItem());
            stmt.setInt(6, Integer.parseInt(capacity.getText()));
            stmt.setString(7, imgPath);
            stmt.setTimestamp(8, new Timestamp(System.currentTimeMillis()));
            stmt.executeUpdate();
            Venue v = new Venue(UUID.randomUUID().toString(), siteName.getText(),
                    city.getText(), address.getText(), (String) type.getSelectedItem(),
                    Integer.parseInt(capacity.getText()), imgPath, new Timestamp(System.currentTimeMillis()));
            Dashboard.Venues.add(v);
            JOptionPane.showMessageDialog(this, "New venue added.");
            parent.addVenueToGui(v);
            this.setVisible(false);
            parent.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not add new venue.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void edit() {
        try {
            String imgName = v.getUuid() + image.getName().substring(image.getName().lastIndexOf("."), image.getName().length());
            String imgPath = "images/venues/" + imgName;
            if (!(image.getName().equals(imgName))) {
                File source = new File(image.getPath());
                File dest = new File(imgPath);
                Utils.copyFile(source, dest);
            }
            PreparedStatement stmt = Dashboard.conn.prepareStatement("UPDATE `venues` SET `uuid`=?,"
                    + "`siteName`=?,`city`=?,`address`=?,`type`=?,"
                    + "`capacity`=?,`picture`=?,`addedOn`=? WHERE `uuid`=?");
            stmt.setString(1, v.getUuid());
            stmt.setString(2, siteName.getText());
            stmt.setString(3, city.getText());
            stmt.setString(4, address.getText());
            stmt.setString(5, (String) type.getSelectedItem());
            stmt.setInt(6, Integer.parseInt(capacity.getText()));
            stmt.setString(7, imgPath);
            stmt.setTimestamp(8, v.getAddedOn());
            stmt.setString(9, v.getUuid());
            stmt.executeUpdate();
            Dashboard.Venues.get(v.getUuid()).edit(v.getUuid(), siteName.getText(),
                    city.getText(), address.getText(), (String) type.getSelectedItem(),
                    Integer.parseInt(capacity.getText()), imgPath, v.getAddedOn());
            JOptionPane.showMessageDialog(this, "Venue updated succesfully.");
            v = new Venue(v.getUuid(), siteName.getText(),
                    city.getText(), address.getText(), (String) type.getSelectedItem(),
                    Integer.parseInt(capacity.getText()), imgPath, v.getAddedOn());
            parent.editVenueInGui(v);
            this.setVisible(false);
            parent.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not update venue.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String fext = file.getName().substring(file.getName().lastIndexOf(".") + 1, file.getName().length());
            if (fext.equals("png") || fext.equals("jpg") || fext.equals("jpeg") || fext.equals("gif")) {
                imgPath.setText(file.getPath());
                this.image = file;
            } else {
                JOptionPane.showMessageDialog(this, "Select a valid image file. \nValid extensions are: (png / jpg/ jpeg/ gif)", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No file was selected.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton btn;
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField city;
    private javax.swing.JLabel errMsg;
    private javax.swing.JLabel imgPath;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField siteName;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
